"""
Tests for secret user-agent token exclusion in detection strategies.

Validates that events generated by Coalmine's own IaC/test operations
(identified by a secret token in the user-agent) are filtered out,
while legitimate access events pass through.
"""
import pytest
import json
from unittest.mock import patch, MagicMock
from datetime import datetime, timedelta

from src.monitors.strategies import (
    CloudWatchLogsQuery, CloudTrailLookup, GcpAuditLogQuery, _is_self_generated
)

IAC_TOKEN = "test-iac-secret-abc123"
TEST_TOKEN = "test-secret-xyz789"


@pytest.fixture(autouse=True)
def mock_exclusion_tokens():
    """Provide known tokens for every test."""
    with patch("src.monitors.strategies.get_ua_exclusion_tokens", return_value=[IAC_TOKEN, TEST_TOKEN]):
        yield


# ─── _is_self_generated ─────────────────────────────────────────────

class TestIsSelfGenerated:
    def test_matches_iac_token(self):
        assert _is_self_generated(f"APN/1.0 coalmine-iac/{IAC_TOKEN}") is True

    def test_matches_test_token(self):
        assert _is_self_generated(f"custom-runner/{TEST_TOKEN}") is True

    def test_legitimate_agent_passes(self):
        assert _is_self_generated("Boto3/1.26.0 Python/3.11") is False

    def test_empty_agent_passes(self):
        assert _is_self_generated("") is False

    def test_none_agent_passes(self):
        assert _is_self_generated(None) is False

    def test_no_tokens_configured(self):
        with patch("src.monitors.strategies.get_ua_exclusion_tokens", return_value=[]):
            assert _is_self_generated("anything") is False


# ─── CloudWatchLogsQuery ─────────────────────────────────────────────

class TestCloudWatchLogsQueryExclusion:
    def _make_log_event(self, event_name, user_agent, event_id="evt-1"):
        ct_payload = {
            "eventName": event_name,
            "sourceIPAddress": "1.2.3.4",
            "userAgent": user_agent,
        }
        return {
            "timestamp": int(datetime.utcnow().timestamp() * 1000),
            "message": json.dumps(ct_payload),
            "eventId": event_id,
        }

    def test_filters_iac_events(self):
        strategy = CloudWatchLogsQuery(filter_pattern='{ ($.eventName = "GetObject") }')
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "bucket-1"
        resource.logging_resource = None
        resource.module_params = None

        client.filter_log_events.return_value = {
            "events": [
                self._make_log_event("GetObject", f"APN/1.0 coalmine-iac/{IAC_TOKEN}", "e1"),
            ]
        }

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 0

    def test_passes_legitimate_events(self):
        strategy = CloudWatchLogsQuery(filter_pattern='{ ($.eventName = "GetObject") }')
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "bucket-1"
        resource.logging_resource = None
        resource.module_params = None

        client.filter_log_events.return_value = {
            "events": [
                self._make_log_event("GetObject", "Boto3/1.26.0 Python/3.11", "e2"),
            ]
        }

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 1
        assert alerts[0].event_name == "GetObject"

    def test_mixed_events(self):
        strategy = CloudWatchLogsQuery(filter_pattern='{ ($.eventName = "GetObject") }')
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "bucket-1"
        resource.logging_resource = None
        resource.module_params = None

        client.filter_log_events.return_value = {
            "events": [
                self._make_log_event("GetObject", f"coalmine-iac/{IAC_TOKEN}", "e1"),
                self._make_log_event("GetObject", "Boto3/1.26.0", "e2"),
                self._make_log_event("GetObject", f"runner/{TEST_TOKEN}", "e3"),
            ]
        }

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 1
        assert alerts[0].external_id == "e2"


# ─── CloudTrailLookup ───────────────────────────────────────────────

class TestCloudTrailLookupExclusion:
    def _make_trail_event(self, event_name, user_agent, event_id="evt-1"):
        ct_event = {
            "eventName": event_name,
            "sourceIPAddress": "10.0.0.1",
            "userAgent": user_agent,
        }
        return {
            "EventId": event_id,
            "EventName": event_name,
            "EventTime": datetime.utcnow(),
            "CloudTrailEvent": json.dumps(ct_event),
        }

    def test_filters_iac_events(self):
        strategy = CloudTrailLookup(lookup_attr_keys=["Username"], event_names=["GetUser"])
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "iam-user-1"
        resource.resource_type = MagicMock(value="AWS_IAM_USER")

        client.lookup_events.return_value = {
            "Events": [
                self._make_trail_event("GetUser", f"OpenTofu/1.0 coalmine-iac/{IAC_TOKEN}"),
            ]
        }

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 0

    def test_passes_legitimate_events(self):
        strategy = CloudTrailLookup(lookup_attr_keys=["Username"], event_names=["ConsoleLogin"])
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "iam-user-1"
        resource.resource_type = MagicMock(value="AWS_IAM_USER")

        client.lookup_events.return_value = {
            "Events": [
                self._make_trail_event("ConsoleLogin", "Mozilla/5.0", "real-evt"),
            ]
        }

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 1


# ─── GcpAuditLogQuery ───────────────────────────────────────────────

class TestGcpAuditLogQueryExclusion:
    def _make_gcp_entry(self, method, user_agent, insert_id="gcp-1"):
        entry = MagicMock()
        entry.payload = {
            "methodName": method,
            "requestMetadata": {
                "callerIp": "35.1.1.1",
                "callerSuppliedUserAgent": user_agent,
            },
        }
        entry.timestamp = datetime.utcnow()
        entry.insert_id = insert_id
        return entry

    def test_filters_iac_events(self):
        strategy = GcpAuditLogQuery(
            filter_template='protoPayload.resourceName:"{resource_id}" AND timestamp >= "{start_time}" AND timestamp <= "{end_time}"'
        )
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "sa@project.iam.gserviceaccount.com"

        client.list_entries.return_value = [
            self._make_gcp_entry("CreateServiceAccountKey", f"Terraform coalmine-iac/{IAC_TOKEN}"),
        ]

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 0

    def test_passes_legitimate_events(self):
        strategy = GcpAuditLogQuery(
            filter_template='protoPayload.resourceName:"{resource_id}" AND timestamp >= "{start_time}" AND timestamp <= "{end_time}"'
        )
        client = MagicMock()
        resource = MagicMock()
        resource.current_resource_id = "sa@project.iam.gserviceaccount.com"

        client.list_entries.return_value = [
            self._make_gcp_entry("CreateServiceAccountKey", "gcloud/400.0", "real-gcp-1"),
        ]

        alerts = strategy.detect(client, resource, datetime.utcnow() - timedelta(minutes=5), datetime.utcnow())
        assert len(alerts) == 1
